# Analysis Configuration for Digimon Knowledge Graph
# Version: 1.0

neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"
  password: "digimon123"
  database: "neo4j"  # default database
  
analysis:
  sample_size: 1249  # Use all data (-1 for all)
  random_seed: 42
  cache_results: true
  output_format: ["png", "html", "json"]
  
  clustering:
    min_community_size: 5
    resolution: 1.0
    iterations: 100
    algorithms:
      - louvain
      - label_propagation
      - girvan_newman
    
  ml:
    test_size: 0.2
    cv_folds: 5
    n_jobs: -1  # Use all cores
    models:
      - random_forest
      - xgboost
      - neural_network
    hyperparameter_tuning: true
    
  visualization:
    color_palette: "viridis"
    figure_dpi: 300
    figure_size: [12, 8]
    interactive: true
    layout_algorithms:
      - spring_layout
      - kamada_kawai
      - circular_layout
    node_size_range: [50, 500]
    edge_width_range: [0.5, 3.0]
    
  statistical_tests:
    alpha: 0.05
    correction_method: "bonferroni"
    min_samples: 30
    
  performance:
    batch_size: 100
    cache_queries: true
    parallel_processing: true
    memory_limit: "8GB"
    
paths:
  data_dir: "../data"
  results_dir: "../results"
  figures_dir: "../results/figures"
  models_dir: "../results/models"
  reports_dir: "../results/reports"
  cache_dir: "../.cache"
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "../results/analysis.log"
  
export:
  notebook_format: ["html", "pdf"]
  figure_formats: ["png", "svg", "pdf"]
  data_formats: ["csv", "json", "parquet"]